Blog app - Views
habasm/BlogApp pull request #6
Opened 2023-05-18 15:24 UTC by habasm

### Ruby requirements
- Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

### Project requirements
- Implement the design from the sneak peek wireframes.
    - Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone)

**Note: Analyze the wireframes deeply and try to identify all the necessary elements and how a user would navigate from one page to another**
    
![All Users page wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_root_users.png) ![Single User page wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_page.png) ![All Posts by a given User page wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png) ![Single Post page wireframe](![image](https://github.com/habasm/BlogApp/assets/111062079/9add21c2-2283-4385-be8c-4605502af20e))

- Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).
- **Hint:** In order to see some posts or comments, you might need to add some data to your database as described [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md#use-models-to-insert-data).

2023-05-18 16:13 UTC, danmainah requested changes
Hi @habasm , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Linter setup correctly and all checks are passing

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- It would be nice if you added the root route in your routes eg `root "users#index"`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-18 16:13 UTC, danmainah commented on app/views/users/show.html.erb
> +    </div>
- [ ] @habasm great work on your user show page, however therre are some issues that need to fixed:

   - [ ] The number of posts is placed wrongly and doesn't have a text indicating the number of posts as shown in the comparison below
   - [ ] The page margin is so small kindly try an increase it, this applies to all other pages.
   - [ ] The biography section doesn't have a closing on the right, it's suppose to be enclosed in a rectangle like posts elements

Wireframe Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://github.com/habasm/BlogApp/assets/61408860/536b4c57-eb53-468d-8f24-6ff392f6ff65)  |![image](https://github.com/habasm/BlogApp/assets/61408860/0f356158-ccf9-460d-a0eb-a8645172629f)

2023-05-18 16:13 UTC, danmainah commented on app/views/posts/index.html.erb
> +        </h4>
- [ ] @habasm great work on your posts page however the number of post counter is placed wrongly and doesn't have a text indicating its the number of posts 
![image](https://github.com/habasm/BlogApp/assets/61408860/004ce543-bb04-4ff8-ad1e-171479fd5ce3)

2023-05-19 07:21 UTC, habasm commented
@danmainah Thanks for your comment and I am modified the code based on yours and fixed other issues on the project.

2023-05-19 08:07 UTC, addod19 requested changes
### Hi @habasm, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Correct Git-flow followed :100: 
- [ ] Great job addressing some of the comments from the previous code reviewer :rocket: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 08:07 UTC, addod19 commented on db/migrate/20230512075205_create_users.rb
> +end
- [ ] We have duplicated migration files, let us kindly resolve it

2023-05-19 08:07 UTC, addod19 commented on db/migrate/20230512094803_create_posts.rb
> +end
- [ ] Here also we have a duplicated file, let us kindly resolve it. It causes problems in migration

2023-05-19 08:19 UTC, habasm commented on app/views/users/index.html.erb
> +            <%= render "user", user: user %>
@addod19 I am not clear about. It's nor full statement. what does it mean "here instead of users we have user"?

2023-05-19 08:33 UTC, habasm commented on app/views/users/index.html.erb
> +            <%= render "user", user: user %>
@addod19 I am not clear about the comment you provided, what does it mean " here instead of users we have user"?

2023-05-19 08:36 UTC, habasm commented
@addod19 Thanks, It's fixed.

2023-05-19 08:37 UTC, addod19 commented on app/views/users/index.html.erb
> +            <%= render "user", user: user %>
@habasm , I'm just trying to give you a hint, you can either change the name of the partial file or change the name of the partial file you render in the view. I hope this is clearly. In all we have a problem in the view, we are unable to see the app as expected

2023-05-19 09:26 UTC, rotimiazeez requested changes
Hi @habasm 😉, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
- Good communication with the CRs 😉
- Descriptive PR 👍🏽

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-05-19 09:26 UTC, rotimiazeez commented on db/migrate/20230512095053_create_comments.rb
> +end
Please note that in your migration folder, you have multiple files with the name `create_comments`. Kindly see to this and make sure its fixed 👍🏽
![Screenshot from 2023-05-19 10-16-18](https://github.com/habasm/BlogApp/assets/44624138/1c2d8d96-4ae3-4650-8839-6679a2964dfc)

2023-05-19 09:26 UTC, rotimiazeez requested changes
Hi @habasm 😉, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
- Good communication with the CRs 😉
- Descriptive PR 👍🏽

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2023-05-19 13:28 UTC, habasm commented
@rotimiazeez  what kind of message your are going to deliver. Absolutely non-usable comments.  Is the programmer give such a comments. ? Just give such comments makes u as reviewer ? 😆

2023-05-19 13:52 UTC, TadesseDev approved these changes
### Hi @habasm 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)



## Highlights
 - [x] Good job making the changes requested by the previous code reviewers. ✅

## Optional suggestions

- [Optional] Dear @habasm, Please try to be professional in the way you communicate with your previous code reviewers. we might be right or wrong in the things we do but we are always required to stay calm and be professional in the way we communicate with others. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 13:53 UTC, TadesseDev commented
> @rotimiazeez I don't want wasting my time for such like tasks....

- [Optional] Dear @habasm, Please try to be professional in the way you communicate with your previous code reviewers. we might be right or wrong in the things we do but we are always required to stay calm and be professional in the way we communicate with others.

2023-05-19 14:05 UTC, habasm commented
@TadesseDev most of the reviewers are fake reviewers, just give comments which are unexpected, if the PR also having not errors they put a request change message. I duplicate a file which can be fixed by deleting it, so how can I am going to an extra review for such comments ?

2023-05-19 14:11 UTC, TadesseDev commented
- dear @habasm, I see your point. But please remember every little comment we ask for request changes is because we have to and it is in the checklist. If you ever feel like the review was not fair, Please don't hesitate to ask for a second view of the review. 

- I let the project pass not because it can be deleted, but because it's a versioning system for migration files that Rails create based on the time step to make an update. this means the last migration will be used anyway to replace the old one. 

- Either way, Please remember, there will always be times when disagreement raise,  `We need to stay calm and professional in our communication` and that is the first rule.

2023-05-19 14:33 UTC, TadesseDev commented
> @TadesseDev most of the reviewers are fake reviewers, just give comments which are unexpected, if the PR also having not errors they put a request change message. I duplicate a file which can be fixed by deleting it, so how can I am going to an extra review for such comments ?

- dear @habasm, I see your point. But please remember every little comment we ask for requests changes is because we have to and it is in the checklist, sometimes it is unclear if something should be required or an optional change. If you ever feel like the review was unfair, Please don't hesitate to ask for a second view. 

- I let the project pass not because it can be deleted, but because it's a versioning system for migration files that Rails create based on the time stamp to make an update. this means the last migration will be used anyway to replace the old one. 

- Either way, Please remember, there will always be times when disagreement raise,  `We need to stay calm and professional in our communication` and that is the first rule.

2023-05-19 14:47 UTC, habasm commented
@TadesseDev I appreciate the way you are explaining. And I tried to be calm and be professional. But sometimes I feel like `What is the important of this comment ?`.

Anyhow thanks brother, I got you!

2023-05-19 14:47 UTC, merged

2023-05-19 14:49 UTC, TadesseDev commented
I feel you too brother. Happy codding 🙏.